### ISSUE TITLE
List index out of range in "associate_tags_with_regions.py"

### ISSUE THREAD

**Issue by abalter** [dariober/SICERpy#3]
I ran:

`$ python $chipseq/SICER.py -c /<path>/bam/mock_input_A.bam -t /home/exacloud/lustre1/<path>/bam/mock_BRD4_A.bam -rt 0 > mock_a_peaks.bed 2> sicermocka.log`

And got this in my log:

```

*** Preprocess raw files to remove reduntant reads
cd /<path>/tmp_sicer_EgQ7hT/tmp_mock_BRD4_A.bam_dir
export PYTHONPATH=/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/lib
/<path>/miniconda2/bin/python /<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/src/remove_redundant_reads_bam.py -t 0 -b /<path>/results/bam/mock_BRD4_A.bam -o /h<path>/tmp_sicer_EgQ7hT/mock_BRD4_A.removed.bam -f 0 -F 4 -q 5

cd /<path>/tmp_sicer_EgQ7hT/tmp_mock_input_A.bam_dir
export PYTHONPATH=/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/lib
/<path>/miniconda2/bin/python /<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/src/remove_redundant_reads_bam.py -t 0 -b /<path>/results/bam/mock_input_A.bam -o /<path>/tmp_sicer_EgQ7hT/mock_input_A.removed.bam -f 0 -F 4 -q 5



*** Partion the genome in windows
cd /<path>/tmp_sicer_EgQ7hT
export PYTHONPATH=/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/lib
/<path>/miniconda2/bin/python /<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/src/run-make-graph-file-by-chrom_bam.py -b /<path>/tmp_sicer_EgQ7hT/mock_BRD4_A.removed.bam -w 200 -i 150 -o /<path>/tmp_sicer_EgQ7hT/summary.bedgraph


*** Find candidate islands exhibiting clustering
export PYTHONPATH=/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/lib
/<path>/miniconda2/bin/python /<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/src/find_islands_in_pr.py --bam /<path>/results/bam/mock_BRD4_A.bam -b /<path>/tmp_sicer_EgQ7hT/summary.bedgraph -w 200 -g 600 -t 0.74 -e 1000  -f /<path>/tmp_sicer_EgQ7hT/scoreisland.bed
Window_size: 200
Gap size: 600
E value is: 1000.0
Total read count: 44053384.0
Genome Length: 3099750718
Effective genome Length: 2293815531
Window average: 3.84105726068
Window pvalue: 0.2
Minimum num of tags in a qualified window: 6
Generate the enriched probscore summary graph and filter the summary graph to get rid of ineligible windows
Determine the score threshold from random background
The score threshold is: 38.137
Make and write islands
	KI270747.1 does not have any islands meeting the required significance
	KI270302.1 does not have any islands meeting the required significance
	KI270710.1 does not have any islands meeting the required significance
	KI270755.1 does not have any islands meeting the required significance
	KI270583.1 does not have any islands meeting the required significance
	KI270322.1 does not have any islands meeting the required significance
	KI270708.1 does not have any islands meeting the required significance
	KI270743.1 does not have any islands meeting the required significance
	KI270510.1 does not have any islands meeting the required significance
	KI270741.1 does not have any islands meeting the required significance
	KI270521.1 does not have any islands meeting the required significance
	KI270587.1 does not have any islands meeting the required significance
	KI270320.1 does not have any islands meeting the required significance
	GL000221.1 does not have any islands meeting the required significance
	KI270310.1 does not have any islands meeting the required significance
	KI270714.1 does not have any islands meeting the required significance
	KI270716.1 does not have any islands meeting the required significance
	KI270737.1 does not have any islands meeting the required significance
	KI270580.1 does not have any islands meeting the required significance
	KI270749.1 does not have any islands meeting the required significance
	KI270423.1 does not have any islands meeting the required significance
	KI270706.1 does not have any islands meeting the required significance
	KI270721.1 does not have any islands meeting the required significance
	KI270753.1 does not have any islands meeting the required significance
	KI270508.1 does not have any islands meeting the required significance
	GL000194.1 does not have any islands meeting the required significance
	KI270582.1 does not have any islands meeting the required significance
	KI270522.1 does not have any islands meeting the required significance
	GL000009.2 does not have any islands meeting the required significance
	GL000226.1 does not have any islands meeting the required significance
	KI270362.1 does not have any islands meeting the required significance
	KI270707.1 does not have any islands meeting the required significance
	KI270734.1 does not have any islands meeting the required significance
	KI270418.1 does not have any islands meeting the required significance
Total number of islands: 19312


*** Calculate significance of candidate islands using the control library
export PYTHONPATH=/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/lib
/<path>/miniconda2/bin/python /<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/src/associate_tags_with_chip_and_control_w_fc_q_bam.py -a /<path>/tmp_sicer_EgQ7hT/mock_BRD4_A.removed.bam -b /<path>/tmp_sicer_EgQ7hT/mock_input_A.removed.bam -d /<path>/tmp_sicer_EgQ7hT/scoreisland.bed -f 150 -t 0.74 -o /<path>/tmp_sicer_EgQ7hT/island-summary.bed
chip library size  44056150
control library size 48890374
Traceback (most recent call last):
  File "/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/src/associate_tags_with_chip_and_control_w_fc_q_bam.py", line 204, in <module>
    main(sys.argv)
  File "/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/src/associate_tags_with_chip_and_control_w_fc_q_bam.py", line 105, in main
    position = associate_tags_with_regions.tag_position(sline, opt.fragment_size)
  File "/<path>/users/balter/chip-seq-analysis/chipseq/SICERpy/SICERpy/lib/associate_tags_with_regions.py", line 37, in tag_position
    if plus.match(sline[5]):
IndexError: list index out of range


```

**Comment by JiangQi1996** [comment]
Have you solved this problem?I got this error too,can you tell me the reason,thanks.

**Comment by abalter** [comment]
Sorry. I never did and moved on to a different peak caller.

**Comment by endrebak** [comment]
It means that one of the lines in the file has fewer than 6 fields. Why I
do not know. Have you tried https://github.com/biocore-ntnu/epic2 ?

**Comment by abalter** [comment]
That's what I ended up using. Worked well for me.

**Comment by dariober** [comment]
Indeed- use https://github.com/biocore-ntnu/epic2 apologies I haven't updated this issue.
